data:
  type: cifar10
  train_dir: ./data/
  test_dir: ./data/
  lsun_categories_train: bedroom_train
  lsun_categories_test: bedroom_test
  img_size: 32
generator:
  name: resnet1 # fix it to 1: the normal resnet
  kwargs:
    nfilter: 32
    nfilter_max: 256
discriminator:
  name: resnet1 # fix it to 1: the normal resnet
  kwargs:
    nfilter: 32
    nfilter_max: 256
z_dist:
  type: gauss
  dim: 256
training:
  gan_type: wgan
  reg_type: none
  reg_param: 0.
  nworkers: 32
  take_model_average: true
  model_average_beta: 0.999
  model_average_reinit: false
  monitoring: tensorboard
  sample_every: 1000
  save_every: 900
  restart_every: -1
  optimizer: rmsprop
  batch_size: 64 ## related to i_size
  lr_g: 0.0001
  lr_d: 0.0001
  out_dir: output/
  out_basename: cifar_pid_
  pid_type: lsgan
  backup_every: 100000
  inception_every: 10000
  pv: 1.
  iv: 5.
  dv: 0.
  improve_d_factor: -1
  improve_d_cycle: 10000
  # model_file: /home/kunxu/mfs/Workspace/GAN_stability/output/0good_ckpt/chkpts/model_00799999.pt
  i_size: 64 ## related to batch_size
  i_buffer_factor: 10
  i_buffer_onestep: 64
  momentum_d: 0. ###
  clip_d: 0. ###
  weight_decay_d: 0. ###
  regularize_output_d: 0. ###
  lr_anneal: 1.
  lr_anneal_every: 150000
  d_steps: 1
  equalize_lr: false
test:
  batch_size: 32
  sample_size: 15
  sample_nrow: 5
  use_model_average: true
  compute_inception: false
  conditional_samples: false
interpolations:
  nzs: 10
  nsubsteps: 75
