data:
  type: lsun
  train_dir: /home/LargeData/LSUN/lsun/
  test_dir: /home/LargeData/LSUN/lsun/
  lsun_categories_train: [bedroom_train]
  lsun_categories_test: [bedroom_test]
  img_size: 256
generator:
  name: resnet1
  kwargs:
    nfilter: 64
    nfilter_max: 1024
    embed_size: 1
discriminator:
  name: resnet1
  kwargs:
    nfilter: 64
    nfilter_max: 1024
    embed_size: 1
z_dist:
  type: gauss
  dim: 256
training:
  gan_type: wgan
  reg_type: none
  reg_param: 0.
  out_dir: output/lsun_bedroom
  pv: 1.
  iv: 0.
  dv: 0.
  momentum_d: 0. ###
  clip_d: 0. ###
  weight_decay_d: 0.0001 ###
  regularize_output_d: 10. ###
  batch_size: 16
  nworkers: 16
  take_model_average: true
  model_average_beta: 0.999
  model_average_reinit: false
  monitoring: tensorboard
  sample_every: 1000
  sample_nlabels: 20
  inception_every: 10000
  save_every: 900
  backup_every: 100000
  restart_every: -1
  optimizer: rmsprop
  lr_g: 0.0001
  lr_d: 0.0001
  lr_anneal: 1.
  lr_anneal_every: 150000
  d_steps: 1
  equalize_lr: false
  model_file: model.pt
test:
  batch_size: 32
  sample_size: 64
  sample_nrow: 8
interpolations:
  nzs: 10
  nsubsteps: 75
